### ISSUE TITLE
疾病管理基本数据集 第6部分 肿瘤病例管理

### ISSUE THREAD

**Issue by fakeyee** [wanghaisheng/healthcaredatastandard#12]
![image](https://cloud.githubusercontent.com/assets/3894482/12258363/285457ba-b949-11e5-8962-00e66f55b90f.png)

DE02.01.017.00   -->   DE02.01.047.00

![image](https://cloud.githubusercontent.com/assets/3894482/12258418/a4fe1508-b949-11e5-855f-96e6ab3ee73f.png)

HDSH04.D6.035 --> HDSH04.06.035

![image](https://cloud.githubusercontent.com/assets/3894482/12258462/e52a58b2-b949-11e5-9ee1-36350b13f2f0.png)

36 --> 06

**Comment by fakeyee** [comment]
请问在系统实现的时候，这些标识符有没有作用呢？

**Comment by wanghaisheng** [comment]
有的公司用到了 有的没有用到  大多以自行维护的数据元标识符为主 这里的标识符多用于映射和参考
