### ISSUE TITLE
我自己fork了你的标准然后重新做了修改

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [wanghaisheng/healthcaredatastandard#19]
在一定程度上大改了你的设计。你后续还会维护这个吗？

**Comment by wanghaisheng** [comment]
看不到你的commit 也看不到你做了哪些修改
我应该会持续把

**Comment by sanbeichahegongheguo** [comment]
我没做commit，因为我的修改挺大，整个文件目录都被我改了，删除的删除，重命名的重命名，解压缩的解压缩，我可能不会给你提交PR，因为真的蛮大的修改。(*/ω＼*)

**Comment by wanghaisheng** [comment]
哦 那你自己做自己的呗
