### ISSUE TITLE
想问一下，为什么这些行业标准文件中，都未定义数据库字段名？

### ISSUE THREAD

**Issue by yamazakitouma** [wanghaisheng/healthcaredatastandard#20]
如题，对于这些数据元标准的文件，只有中文数据元名称，和相关标识符，怎么没有定义数据库字段存储的英文字段名？

**Comment by wanghaisheng** [comment]
因为这些都不是严格意义上的数据模型  充其量是信息模型
直接用首字母连写得了 如果你是在找中英文映射的话 那很难

**Comment by yamazakitouma** [comment]
也就是说，国家并未对病历，像卫健委规定病案首页数据库标准那样，规定病历相关的数据库设计标准，只是给了一个元数据的标准，具体数据库设计并未定义。

**Comment by wanghaisheng** [comment]
规定病案首页数据库标准
从我的角度 国家也么有定义这个，
只不过这类业务有直报系统，直报系统会对这些业务的字段 数据库字段做要求

**Comment by yamazakitouma** [comment]
明白了，这么一说也是，我看医保那边给的 数据库 标准，也是因为 医保的相关业务系统 才做了一套数据库标准。

**Comment by wanghaisheng** [comment]
是 我们这边所谓的数据对接 就是数据库对接，
他们甚至会强制要求/提供一套数据库结构作为医疗机构和管理部门系统的中转枢纽
